# Generated by Django 4.0.5 on 2022-06-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_functions_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'пол животного', 'verbose_name_plural': 'пол животных'},
        ),
        migrations.AlterModelOptions(
            name='animal_category',
            options={'verbose_name': 'категория животного', 'verbose_name_plural': 'категории животных'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'услуга', 'verbose_name_plural': 'услуги'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'Временной промежуток', 'verbose_name_plural': 'Временные промежутки'},
        ),
    ]
