# Generated by Django 3.2.14 on 2022-07-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_functions_website', '0002_alter_animal_options_alter_animal_category_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Animal_Category',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'цену', 'verbose_name_plural': 'цены'},
        ),
    ]
