# Generated by Django 3.2.14 on 2022-07-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_functions_website', '0003_auto_20220716_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Группа цены',
                'verbose_name_plural': 'Группы цен',
            },
        ),
    ]
