# Generated by Django 3.2.14 on 2022-07-16 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_functions_website', '0004_groupprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='title',
        ),
        migrations.AddField(
            model_name='price',
            name='group_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_functions_website.groupprice'),
        ),
        migrations.AlterField(
            model_name='groupprice',
            name='name',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True),
        ),
    ]
