# Generated by Django 3.2.14 on 2022-07-16 23:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_functions_website', '0005_auto_20220717_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprice',
            name='position',
            field=models.IntegerField(default=uuid.uuid4),
        ),
    ]
