# Generated by Django 3.2.14 on 2022-07-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_functions_website', '0011_alter_groupprice_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Основная часть')),
            ],
            options={
                'verbose_name': 'статью',
                'verbose_name_plural': 'статьи',
            },
        ),
    ]
